# High Level Configuration
inputDir: 'resources'
outputDir: 'results'
modelName: 'BBIN'
region: 'GLOBAL'
slug: 'node1-node2-99-2029-584546' # run id: 2

# Scenario Name
scenario: 'no_tax'

# Temporal Parameters
startYear: 2015
endYear: 2050
daytype: False
dayparts:
  #daypart : [start_hour (inclusive), end_hour (exclusive)]
  D1: [0, 6]
  D2: [6, 12]
  D3: [12, 18]
  D4: [18, 24]

seasons:
  #season : [month 1, month 2, ...] (all inclusive)
  S1: [1, 2, 3,]
  S2: [4, 5, 6]
  S3: [7, 8, 9]
  S4: [10, 11, 12]

# Spatial Parameters
geographic_scope:
  - 'IND'

crossborderTrade: True

# Emission Parameters
emission_penalty: 100 # M$/MT CO2

# Investment Parameters
no_invest_technologies:
  - 'GEO'
  - 'CSP'
  - 'WAV'
  - 'BIO'
  - 'URN'

# Result Parameters
results_by_country: True

user_defined_capacity:
  #technology: [capacity, first_year, lifetime]
  TRNINDEAINDSO: [3, 2027, 50]
